### ISSUE TITLE
java: error reading /Users/../m2/repository/io/zipkin/brave/brave/5.13.2/brave-5.13.2.jar; zip file is empty

### ISSUE THREAD

**Issue by kassymbekoff** [amigoscode/microservices#7]
Hello, after adding Spring Cloud Sleuth dependency I got this error on run application
I moved to the this folder  /Users/../m2/repository/io/zipkin/brave/brave/5.13.2/brave-5.13.2.jar and see that brave-5.13.2.jar file is really has 0 byte.
Any suggestions?

**Comment by negesti** [comment]
@kassymbekoff .m2 is your local mvn repository. just remove the folder and let mvn re-download the file
